import { NameValue } from '../types/NameValue'

export const Genres: NameValue[] = [
  { value: 'Action', name: 'Action' },
  { value: 'Adult', name: 'Adult' },
  { value: 'Adventure', name: 'Adventure' },
  { value: 'Animation', name: 'Animation' },
  { value: 'Biography', name: 'Biography' },
  { value: 'Comedy', name: 'Comedy' },
  { value: 'Crime', name: 'Crime' },
  { value: 'Documentary', name: 'Documentary' },
  { value: 'Drama', name: 'Drama' },
  { value: 'Family', name: 'Family' },
  { value: 'Fantasy', name: 'Fantasy' },
  { value: 'Film Noir', name: 'FilmNoir' },
  { value: 'Game Show', name: 'GameShow' },
  { value: 'History', name: 'History' },
  { value: 'Horror', name: 'Horror' },
  { value: 'Musical', name: 'Musical' },
  { value: 'Music', name: 'Music' },
  { value: 'Mystery', name: 'Mystery' },
  { value: 'News', name: 'News' },
  { value: 'Reality-TV', name: 'RealityTV' },
  { value: 'Romance', name: 'Romance' },
  { value: 'Sci-Fi', name: 'SciFi' },
  { value: 'Short', name: 'Short' },
  { value: 'Sport', name: 'Sport' },
  { value: 'Talk-Show', name: 'TalkShow' },
  { value: 'Thriller', name: 'Thriller' },
  { value: 'War', name: 'War' },
  { value: 'Western', name: 'Western' },
]
