import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useCallback, useEffect, useState } from 'react'
import Header from '../../../components/header'
import styles from '../../../styles/Pages.module.scss'
import { useRouter } from 'next/router'
import { MovieInfo } from '../../../types/MovieInfo'
import MovieDetail from '../../../components/movie-detail'
import { titleBase } from '../../../constants/appConstants'
const movieData = require('../../../constants/movies-sample-data.json')

const TitlePage: NextPage = () => {
  const router = useRouter()
  const { id } = router.query
  const [movie, setMovie] = useState<MovieInfo>()
  const [error, setError] = useState('')
  const title = movie?.title ? titleBase + ' - ' + movie?.title : titleBase

  const extractIMDBID = useCallback(() => {
    if (id) {
      const idString = id as string
      const firstDashIndex = idString.indexOf('-')
      const iMDBID = idString.substring(0, firstDashIndex)

      const filteredMovie = movieData.find(
        (data: MovieInfo) => data.imdbID === iMDBID
      ) as MovieInfo | undefined
      if (filteredMovie && filteredMovie.imdbID) {
        setMovie(filteredMovie)
        return
      }
      setError("Specified Title doesn't exist on the database")
    }
  }, [id])

  useEffect(() => {
    extractIMDBID()
  }, [extractIMDBID])

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={`${styles.content} ${styles['column-direction']}`}>
        <div className={styles['back-button-row']}>
          <div className={styles['back-button']} onClick={() => router.back()}>
            &#60;BACK
          </div>
        </div>
        {error}
        {movie && <MovieDetail movie={movie} />}
      </div>
    </div>
  )
}

export default TitlePage
