import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import Header from '../../components/header'
import styles from '../../styles/Pages.module.scss'
import dynamic from 'next/dynamic'
import { MovieInfo } from '../../types/MovieInfo'
import { useRouter } from 'next/router'
import { titleBase } from '../../constants/appConstants'
import Query from '../../components/query'
import { MovieType } from '../../enums/MovieType'
const movieData = require('../../constants/movies-sample-data.json')

// make this dynamic, so that the images are loaded dynamically and not via SSR,
// which causes problems
const SearchResults = dynamic(() => import('../../components/search-results'), {
  ssr: false,
})

const Home: NextPage = () => {
  const router = useRouter()
  const { keyword, type } = router.query
  const resultForText = keyword
    ? 'Result for: ' + keyword
    : type
    ? `Filter ${type === MovieType.Movie ? 'movies' : 'TV series'}`
    : ''
  const title = keyword || type ? titleBase + ' - ' + resultForText : ''

  const renderSearchResults = () => {
    if (!keyword && !type) {
      return null
    }

    if (keyword) {
      const movies = movieData.filter((movie: MovieInfo) => {
        const regexp = new RegExp(keyword as string, 'i')
        return regexp.test(movie.title)
      })
      return movies && movies.length > 0 ? (
        <SearchResults movies={movies} />
      ) : (
        <p className={styles['no-results']}>
          No results found. Try searching for a different keyword
        </p>
      )
    }

    // Search by type
    const movies = movieData.filter((movie: MovieInfo) => movie.type === type)
    return movies && movies.length > 0 ? (
      <SearchResults movies={movies} />
    ) : (
      <p className={styles['no-results']}>No results found.</p>
    )
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className={`${styles.content} ${styles['column-direction']}`}>
        <div className={styles['query-mobile']}>
          <Query />
        </div>
        <div className={styles['title-row']}>
          <div className={styles.title}>{resultForText}</div>
          <div className={styles['back-button']} onClick={() => router.back()}>
            &#60;BACK
          </div>
        </div>
        {renderSearchResults()}
      </div>
    </div>
  )
}

export default Home
