import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useCallback, useEffect, useState } from 'react'
import Header from '../../components/header'
import styles from '../../styles/Pages.module.scss'
import dynamic from 'next/dynamic'
import { MovieInfo } from '../../types/MovieInfo'
import { useRouter } from 'next/router'
import { titleBase } from '../../constants/appConstants'
import Query from '../../components/query'
import { MovieType } from '../../enums/MovieType'
import { useApolloClient } from '@apollo/client'
import { getTitlesByKeyword, getTitlesByType } from '../../queries'
import Spinner from '../../components/spinner'

// make this dynamic, so that the images are loaded dynamically and not via SSR,
// which causes problems
const SearchResults = dynamic(() => import('../../components/search-results'), {
  ssr: false,
})

type MovieResponse = {
  movie: MovieInfo[]
}

// Note: we couldn't use useLazyQuery due to the behaviour outlined in
// https://github.com/apollographql/apollo-client/issues/5912. Was forced to use useApolloClient instead

const Home: NextPage = () => {
  const router = useRouter()
  const { keyword, type } = router.query
  const [queryExecuted, setQueryExecuted] = useState(false)
  const [queryKeyword, setQueryKeyword] = useState('')
  const [queryType, setQueryType] = useState('')
  const client = useApolloClient()
  const [movies, setMovies] = useState<MovieInfo[]>([])
  const resultForText = queryKeyword
    ? 'Result for: ' + queryKeyword
    : queryType
    ? `Filter ${queryType === MovieType.Movie ? 'movies' : 'TV series'}`
    : ''
  const title =
    queryKeyword || queryType ? titleBase + ' - ' + resultForText : ''
  const [loading, setLoading] = useState(false)
  const [loadingError, setLoadingError] = useState(false)

  const executeQuery = useCallback(
    async (queryKeywordInt: string, queryTypeInt: string) => {
      if (!queryKeywordInt && !queryTypeInt) {
        return
      }

      try {
        setLoading(true)
        if (queryKeywordInt) {
          const response = await client.query<MovieResponse>({
            query: getTitlesByKeyword,
            variables: {
              titleSearch: `%${queryKeywordInt}%`,
            },
            fetchPolicy: 'no-cache',
          })
          if (response.data && response.data.movie.length > 0) {
            setMovies(response.data.movie)
          }
        }

        if (queryTypeInt) {
          const response = await client.query<MovieResponse>({
            query: getTitlesByType,
            variables: {
              type: queryTypeInt,
            },
            fetchPolicy: 'no-cache',
          })
          if (response.data && response.data.movie.length > 0) {
            setMovies(response.data.movie)
          }
        }
      } catch {
        setLoadingError(true)
      } finally {
        setLoading(false)
      }

      setQueryExecuted(true)
    },
    [client]
  )

  useEffect(() => {
    executeQuery(queryKeyword, queryType)
    // Note: purposely left out executeQuery from dependancy array.
    // We don't want to re-execute when executeQuery changes
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [queryKeyword, queryType])

  useEffect(() => {
    if (keyword) {
      setQueryKeyword(keyword as string)
      setQueryType('')
    } else if (type) {
      setQueryKeyword('')
      setQueryType(type as string)
    }
  }, [keyword, type])

  const renderSearchResults = () => {
    if (!queryExecuted || loading || loadingError) {
      return null
    }

    if (queryKeyword && movies.length === 0) {
      return (
        <p className={styles['no-results']}>
          No results found. Try searching for a different keyword
        </p>
      )
    }

    if (queryType && movies.length === 0) {
      return <p className={styles['no-results']}>No results found</p>
    }

    return <SearchResults movies={movies} />
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Header />
      <div className={`${styles.content} ${styles['column-direction']}`}>
        <div className={styles['query-mobile']}>
          <Query />
        </div>
        <div className={styles['title-row']}>
          <div className={styles.title}>{resultForText}</div>
          <div className={styles['back-button']} onClick={() => router.back()}>
            &#60;BACK
          </div>
        </div>
        {loading && <Spinner />}
        {loadingError && <p>Error occured while fetching titles</p>}
        {renderSearchResults()}
      </div>
    </div>
  )
}

export default Home
