/* eslint-disable @next/next/no-page-custom-font */
import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import Header from '../components/header'
import HeroCarousel from '../components/hero-carousel'
import Query from '../components/query'
import { titleBase } from '../constants/appConstants'
import styles from '../styles/Pages.module.scss'
import { MovieInfo } from '../types/MovieInfo'
const movieData = require('../constants/movies-sample-data.json')

// make this dynamic, so that the images are loaded dynamically and not via SSR,
// which causes problems
const MovieSection = dynamic(() => import('../components/movie-section'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{titleBase}</title>
        <meta name='description' content='Generated by create next app' />
        <link
          href='https://fonts.googleapis.com/css2?family=Amatic+SC&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Header />
      <div className={`${styles.content} ${styles['column-direction']}`}>
        <div className={styles['query-mobile']}>
          <Query />
        </div>
        <HeroCarousel />
        <MovieSection
          sectionTitle='Featured'
          movies={movieData.filter((movie: MovieInfo) => movie.featured)}
        />
      </div>
    </div>
  )
}

export default Home
