import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import React from 'react'
import Header from '../components/header'
import styles from '../styles/Home.module.scss'
const movieData = require('../constants/movies-sample-data.json')

// make this dynamic, so that the images are loaded dynamically and not via SSR,
// which causes problems
const MovieSection = dynamic(() => import('../components/movie-section'), {
  ssr: false,
})

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ultra Movie Shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className={styles.content}>
        <MovieSection sectionTitle='Featured' movies={movieData} />
      </div>
    </div>
  )
}

export default Home
